### PR TITLE
Correct paths to conf files

### PR DESCRIPTION
**Pull request by Oper18**
Correct pathes to conf files as absolute for using this Keras as library and correct error with showing image

### CODE REVIEW

**Comment by Borda** [comment]
@Oper18 thank you for your suggestion, may you first resolve conflicts to be aligned with actual master... Thx

**Comment by Oper18** [comment]
I'm resolve rebase my changes in my commit

**Comment by Borda** [comment]
Thank you, it seems that you are still using the old past structure, now the `yolo.py` is in package `yolo3` and I guess that there is `yolo_video.py` anymore... pls could you check it...

**Comment by Oper18** [comment]
All my changes was around yolo and yolo_video)))

**Review by Borda — CHANGES_REQUESTED** [review]
pls, set your "upstream" to point to this repository and rebase it
```
git remote add upstream https://github.com/Borda/keras-yolo3.git
git rebase upstream/master
```

**Comment by Borda** [comment]
@Oper18 mind finish it or shall we close it?

**Pull request closed without merging**
