### PR TITLE
port to TensorFlow 2.0

### LINKED ISSUE #21: porting to TF 2.0
Since this Keras implementation is based on TensorFlow, it makes sense to port ti to `tf.keras` in TensorFlow 2.0 or higher. This move may solve the issue with multi-GPU training #20 

https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/

### PR DESCRIPTION
**Pull request by 6293**
Replaced deprecated modules and functions.

### CODE REVIEW

**Comment by Borda** [comment]
@z8674558 thx, it seems that also test need to be adjusted according to new returns values
as this change is not back-compatible to TF 1, mind also update min TF version in requirements

**Comment by z8674558** [comment]
@Borda okay, I will modify the test.

**Comment by z8674558** [comment]
@Borda modified tox.ini, requirements.txt and .travis.yml to pass the tests. Also, I fixed docstring to pass doctest.

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@z8674558 Thank you!

**Pull request merged**
